### PR TITLE
Fix UKSM patch name for 5.7

### PR DESCRIPTION
**Pull request by firasuke**

### CODE REVIEW

**Comment by sirlucjan** [comment]
Thanks a lot. Apparently a mistake has crept in.

**Comment by firasuke** [comment]
No worries, keep up the good work.

Also, is this patch any different (as in tested to work without errors, since some previous versions of the original patch failed to patch certain files of certain kernel versions) from the [original one](https://github.com/dolohow/uksm/blob/master/v5.x/uksm-5.7.patch)?

**Comment by sirlucjan** [comment]
I don't know what exactly it's about, so I'll answer two possible scenarios.

No, I placed it because I wasn't waiting for the official release for version 5.7 - this one came out a little later and it's basically exactly the same.

And it differs from uksm-patches(-v1) version only that the previous one didn't overlap with other patches I use as well. Basically it's the only reason why I added it...

The problem will appear only in kernel 5.8 - there were so big changes here that you will have to rewrite the patch in at least a few places

**Comment by firasuke** [comment]
I see, thanks for your time and effort.

**Pull request merged**
